export const ActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODUCTS : 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCTS : 'REMOVE_SELECTED_PRODUCTS',
    DELETE_PRODUCTS : 'DELETE_PRODUCTS',
    PAGINATION_PRODUCTS : 'PAGINATION_PRODUCTS',
    ADD_PRODUCT : 'ADD_PRODUCT',
    REMOVE_ADDED_PRODUCT : 'REMOVE_ADDED_PRODUCT',
    UPDATE_PRODUCT : 'UPDATE_PRODUCT'
}